CREATE TABLE IF NOT EXISTS forks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  repo_id INT NOT NULL,
  user_id INT NOT NULL,
  fork_url VARCHAR(500) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NULL,
  FOREIGN KEY (repo_id) REFERENCES repos(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
